AMPscript extensions checker
SalesforceLabs/ampscript-core pull request #29
Opened 2024-03-13 12:32 UTC by FiB3

The goal of this PR is to help users regarding the issues #13 & #16 by notifying them about the currently incompatible extensions.

2024-03-13 15:44 UTC, lbuesching requested changes

2024-03-13 15:44 UTC, lbuesching commented on src/vscode/src/checks.ts
> +				vscode.window.showInformationMessage(`MCFS [AMPScript] extension is currently not supported by AMPscript Core.`);
Let's update this message to convey what not supported means.

"The extension MCFS [AMPScript] is incompatible with AMPscript Core and will prevent AMPscript Core from debugging AMPscript."

2024-03-13 15:44 UTC, lbuesching commented on src/vscode/src/checks.ts
> +			handler: () => true
Was this to test a positive test case?

2024-03-13 20:05 UTC, FiB3 commented
Ok, updated the warning message. :)
You are right, the "beautyAmp" was more of an example and test case. I've removed it and replaced it with a comment.

2024-03-18 17:53 UTC, lbuesching commented
Backward compatibility checks are fine, no changes from this change.

2024-03-18 17:53 UTC, merged